### ISSUE TITLE
BUG : ___BufferUnderFlowException occurred while server receive header data

### ISSUE THREAD

**Issue by kbh97102** [Thunder-cut-2020/WhiteBoard-Server#10]
**Describe the bug**
When Server get data type and data size BufferUnderFlowException is occurred
But don't repeat this error after client reconnect
( getChar or getInt  method occurred this error in ClientInformation class)

**To Reproduce**
1, Execute server
2. Connect client
3. Send data client to server until error appeared (I can't specify when error occurred)

**Expected behavior**
Server received many data in little time

**(optional) Screenshots**

**Additional context**
I tried send data with 2 second delay, this time error don't appeared
But 25 millisecond delay, error appeared

**Comment by sjy5386** [comment]
I think we should do a performance test at our next meeting.
- It is difficult to reproduce the situation.
- The test server is located abroad, which is likely to cause communication failures.
