### ISSUE TITLE
BUG : Occur ConcurrentModificationException when connect after disconnect.

### ISSUE THREAD

**Issue by Kasania** [Thunder-cut-2020/WhiteBoard-Server#14]
**Describe the bug**
I test multi client connection.
When i disconnect a host and connect another host, the connection is fail.     
Try to reconnect, connection is success but dest_id is weird.

**To Reproduce**
1. Connect multiple client to server(At least 6).
2. Disconnect some client.
3. Connect a Client.
3. Show Exception.

**Expected behavior**
Connect a client without exception after disconnect

**(optional) Screenshots**
ServerSide :
![image](https://user-images.githubusercontent.com/17539650/74674185-3322a500-51f4-11ea-9695-21e90aa040ea.png)
ClientSide:
![image](https://user-images.githubusercontent.com/17539650/74674946-c9a39600-51f5-11ea-9163-ad5215e1ad82.png)

**Comment by sjy5386** [comment]
This issue is related to **synchronization**.
If the number of connected clients changes, server should stop sending data temporarily.
