### ISSUE TITLE
BUG : Client ID Mismatch

### ISSUE THREAD

**Issue by Kasania** [Thunder-cut-2020/WhiteBoard-Server#15]
**Describe the bug**
I test multi client connection.    
When i connect 3rd client, image is drew weird position.
So i checked up client codes, but it was clean.
I check src_id and dest_id, the id was not matched with connection number.

**To Reproduce**
1. Connect multiple client(At least 3)
2. See error

**Expected behavior**
The server make correct id

**(optional) Screenshots**

![image](https://user-images.githubusercontent.com/17539650/74675726-7f231900-51f7-11ea-8daa-7e2125d31635.png)

**Additional context**
ID was increased by connection number.
0->1->3->6->10->15->21->28...

**Comment by sjy5386** [comment]
What branch did you test on?
_develop_? _socket_?

**Comment by Kasania** [comment]
I used most latest version, even more than all of upstream branch.

**Comment by sjy5386** [comment]
> 
> 
> I used most latest version, even more than all of upstream branch.

I think it probably doesn't have that bug in the latest version of upstream.

**Comment by Kasania** [comment]
> > I used most latest version, even more than all of upstream branch.
> 
> I think it probably doesn't have that bug in the latest version of upstream.

@kbh97102 Please check this out.

**Comment by sjy5386** [comment]
### Troubleshooting

- _ClientInformation_ class does **not** have an _ID_.
- Get _ID_ from _SyncServer_ class.
